language: java
script:
  - mvn clean package docker:build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/spider-monkey
jdk:
  - oraclejdk8

services:
  - docker

notifications:
  email:
    - nicholasinengland@hotmail.com